/*
 * Automatically generated by jrpcgen 1.0.7 on 1/12/15 9:50 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
/**
 * A collection of constants used by the "getAccType" ONC/RPC program.
 */
public interface getAccType {
    public static final int ID_NUM_SIZE = 5;
    public static final int BANK_ACCOUNT_PROG = 9999;
    public static final int NO_ACC = 0;
    public static final int GET_ACC_TYPE_1 = 1;
    public static final int ACC_VERS_1 = 1;
}
// End of getAccType.java
