/*
 * Automatically generated by jrpcgen 1.0.7 on 1/12/15 9:50 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

import java.net.InetAddress;

import org.acplt.oncrpc.server.*;

/**
 */
public abstract class getAccTypeServerStub extends OncRpcServerStub implements OncRpcDispatchable {

    public getAccTypeServerStub()
           throws OncRpcException, IOException {
        this(0);
    }

    public getAccTypeServerStub(int port)
           throws OncRpcException, IOException {
        this(null, port);
    }

    public getAccTypeServerStub(InetAddress bindAddr, int port)
           throws OncRpcException, IOException {
        info = new OncRpcServerTransportRegistrationInfo [] {
            new OncRpcServerTransportRegistrationInfo(getAccType.BANK_ACCOUNT_PROG, 1),
        };
        transports = new OncRpcServerTransport [] {
            new OncRpcUdpServerTransport(this, bindAddr, port, info, 32768),
            new OncRpcTcpServerTransport(this, bindAddr, port, info, 32768)
        };
    }

    public void dispatchOncRpcCall(OncRpcCallInformation call, int program, int version, int procedure)
           throws OncRpcException, IOException {
        if ( version == 1 ) {
            switch ( procedure ) {
            case 1: {
                acc_id_num args$ = new acc_id_num();
                call.retrieveCall(args$);
                XdrByte result$ = new XdrByte(GET_ACC_TYPE_1(args$));
                call.reply(result$);
                break;
            }
            default:
                call.failProcedureUnavailable();
            }
        } else {
            call.failProgramUnavailable();
        }
    }

    public abstract byte GET_ACC_TYPE_1(acc_id_num arg1);

}
// End of getAccTypeServerStub.java
